# Generated by Django 4.2.16 on 2026-06-29 17:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextualSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions_snapshot', models.JSONField(default=list)),
                ('summary_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('featured_characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('original_language', models.CharField(default='auto', max_length=10)),
                ('raw_excel_path', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['primary_show', 'episode_number'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('he', 'Hebrew'), ('en', 'English')], max_length=5)),
                ('translated_rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='episodes.episode')),
            ],
            options={
                'ordering': ['episode', 'language'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField()),
                ('key_topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='episodes.episode')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_order', models.PositiveIntegerField(blank=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='episodes.episode')),
            ],
            options={
                'ordering': ['season', 'episode_order'],
            },
        ),
    ]
