# Generated by Django 4.2.16 on 2026-06-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodes', '0001_initial'),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodeseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='primary_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='shows.show'),
        ),
        migrations.AddField(
            model_name='episode',
            name='seasons',
            field=models.ManyToManyField(related_name='episodes', through='episodes.EpisodeSeason', to='shows.season'),
        ),
        migrations.AddField(
            model_name='contextualsummary',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextual_summaries', to='episodes.episode'),
        ),
    ]
