# Generated by Django 4.2.16 on 2026-06-29 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contextualsummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextual_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='episodetranslation',
            unique_together={('episode', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='episodeseason',
            unique_together={('episode', 'season')},
        ),
    ]
