# Generated by Django 4.2.16 on 2026-09-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0004_character_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesummary',
            name='brief_summary',
            field=models.TextField(blank=True),
        ),
    ]
