apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speechy-postgres
  labels:
    app: speechy
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
