const BASE = '/api';

export const API = {
  AUTH: {
    LOGIN: `${BASE}/auth/login/`,
    LOGOUT: `${BASE}/auth/logout/`,
    ME: `${BASE}/auth/me/`,
    REGISTER: `${BASE}/auth/register/`,
  },
  SHOWS: `${BASE}/shows/`,
  SHOW: (id) => `${BASE}/shows/${id}/`,
  SHOW_SEASONS: (id) => `${BASE}/shows/${id}/seasons/`,
  SHOW_QUESTIONS: (id) => `${BASE}/shows/${id}/questions/`,
  SHOW_KNOWLEDGE: (id) => `${BASE}/shows/${id}/knowledge/`,
  SEASONS: `${BASE}/seasons/`,
  SEASON: (id) => `${BASE}/seasons/${id}/`,
  SEASON_EPISODES: (id) => `${BASE}/seasons/${id}/episodes/`,
  SEASON_QUESTIONS: (id) => `${BASE}/seasons/${id}/questions/`,
  SEASON_KNOWLEDGE: (id) => `${BASE}/seasons/${id}/knowledge/`,
  EPISODES: `${BASE}/episodes/`,
  EPISODE: (id) => `${BASE}/episodes/${id}/`,
  EPISODE_UPLOAD: (id) => `${BASE}/episodes/${id}/upload/`,
  EPISODE_TRANSLATE: (id) => `${BASE}/episodes/${id}/translate/`,
  EPISODE_SUMMARIZE: (id) => `${BASE}/episodes/${id}/summarize/`,
  EPISODE_CONTEXTUAL: (id) => `${BASE}/episodes/${id}/contextual/`,
  EPISODE_TRANSLATIONS: (id) => `${BASE}/episodes/${id}/translations/`,
  EPISODE_SUMMARY: (id) => `${BASE}/episodes/${id}/summary/`,
  EPISODE_CONTEXTUAL_SUMMARIES: (id) => `${BASE}/episodes/${id}/contextual-summaries/`,
  KNOWLEDGE: (id) => `${BASE}/knowledge/${id}/`,
  QUESTION: (id) => `${BASE}/questions/${id}/`,
  JOBS: `${BASE}/jobs/`,
  JOB: (id) => `${BASE}/jobs/${id}/`,
  JOB_STOP: (id) => `${BASE}/jobs/${id}/stop/`,
  USERS: `${BASE}/users/`,
  USER: (id) => `${BASE}/users/${id}/`,
  ORGANIZATIONS: `${BASE}/organizations/`,
  ORGANIZATION: (id) => `${BASE}/organizations/${id}/`,
  API_KEYS: `${BASE}/api-keys/`,
  API_KEY_REVOKE: (id) => `${BASE}/api-keys/${id}/revoke/`,
  SESSIONS: `${BASE}/sessions/`,
  SESSION_REVOKE: (id) => `${BASE}/sessions/${id}/revoke/`,
  AUDIT_LOGS: `${BASE}/audit-logs/`,
};
