const BASE = '/api';

export const API = {
  AUTH: {
    LOGIN: `${BASE}/auth/login/`,
    LOGOUT: `${BASE}/auth/logout/`,
    ME: `${BASE}/auth/me/`,
    REGISTER: `${BASE}/auth/register/`,
  },
  SHOWS: `${BASE}/shows/`,
  SHOW: (id: string): string => `${BASE}/shows/${id}/`,
  SHOW_CHILDREN: (id: string): string => `${BASE}/shows/${id}/children/`,
  SHOW_TREE: (id: string): string => `${BASE}/shows/${id}/tree/`,
  SHOW_EPISODES: (id: string): string => `${BASE}/shows/${id}/episodes/`,
  SHOW_QUESTIONS: (id: string): string => `${BASE}/shows/${id}/questions/`,
  SHOW_KNOWLEDGE: (id: string): string => `${BASE}/shows/${id}/knowledge/`,
  SHOW_SEARCH: (id: string): string => `${BASE}/shows/${id}/search/`,
  SHOW_UPLOAD: (id: string): string => `${BASE}/shows/${id}/upload/`,
  SHOW_MEMBERS: (id: string): string => `${BASE}/shows/${id}/members/`,
  SHOW_MEMBER: (showId: string, memberId: string): string => `${BASE}/shows/${showId}/members/${memberId}/`,
  EPISODES: `${BASE}/episodes/`,
  EPISODE: (id: string): string => `${BASE}/episodes/${id}/`,
  EPISODE_UPLOAD: (id: string): string => `${BASE}/episodes/${id}/upload/`,
  EPISODE_TRANSLATE: (id: string): string => `${BASE}/episodes/${id}/translate/`,
  EPISODE_SUMMARIZE: (id: string): string => `${BASE}/episodes/${id}/summarize/`,
  EPISODE_CONTEXTUAL: (id: string): string => `${BASE}/episodes/${id}/contextual/`,
  EPISODE_TRANSCRIPTS: (id: string): string => `${BASE}/episodes/${id}/transcripts/`,
  EPISODE_TRANSLATIONS: (id: string): string => `${BASE}/episodes/${id}/translations/`,
  EPISODE_SUMMARY: (id: string): string => `${BASE}/episodes/${id}/summary/`,
  EPISODE_CONTEXTUAL_SUMMARIES: (id: string): string => `${BASE}/episodes/${id}/contextual-summaries/`,
  KNOWLEDGE: (id: string): string => `${BASE}/knowledge/${id}/`,
  QUESTION: (id: string): string => `${BASE}/questions/${id}/`,
  JOBS: `${BASE}/jobs/`,
  JOB: (id: string): string => `${BASE}/jobs/${id}/`,
  JOB_STOP: (id: string): string => `${BASE}/jobs/${id}/stop/`,
  USERS: `${BASE}/users/`,
  USER: (id: string): string => `${BASE}/users/${id}/`,
  ORGANIZATIONS: `${BASE}/organizations/`,
  ORGANIZATION: (id: string): string => `${BASE}/organizations/${id}/`,
  API_KEYS: `${BASE}/api-keys/`,
  API_KEY_REVOKE: (id: string): string => `${BASE}/api-keys/${id}/revoke/`,
  SESSIONS: `${BASE}/sessions/`,
  SESSION_REVOKE: (id: string): string => `${BASE}/sessions/${id}/revoke/`,
  AUDIT_LOGS: `${BASE}/audit-logs/`,
};
