apiVersion: v1
kind: Service
metadata:
  name: speechy-redis
  labels:
    app: speechy
    component: redis
spec:
  selector:
    app: speechy
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
